--- 
- name: copy files from one loc to another
  hosts: all
  become: true
  tasks:
  - name: copy index,html file
    copy:
      src: /opt/ansible/index.html
      dest: /home/ansadmin
      mode: 755
      owner: appuser