---
- name: install packages with multi tasks
  hosts: web-servers
  become: true
  tasks:
  - name: install package with yum
    yum:
      name: httpd
      state: installed
  - name: start httpd service 
    service:
      name: httpd
      state: started
  