---
- name: install httpd apache2 with ansible playbook
  hosts: all
  become: true
  tasks:
  - name: install httpd - linux servers
    yum:
      name: httpd
      state: installed
    when: ansible_os_family=="RedHat"
  - name: start service httpd - linux servers 
    service: 
     name: httpd
     state: started 
    when: ansible_os_family=="RedHat"
  - name: install apache2 - ubuntu server 
    apt:
      name: apache2
      state: present 
    when: ansible_os_family=="Debian"
  - name: start service - ubuntu server
    service: 
      name: apache2
      state: started  
    when: ansible_os_family=="Debian"