---
- name: uninstall httpd apache2 with ansible playbook
  hosts: all
  become: true
  tasks:
  - name: stop service httpd - linux servers 
    service: 
     name: httpd
     state: stopped 
    when: ansible_os_family=="RedHat"
  - name: uninstall httpd - linux servers
    yum:
     name: httpd
     state: absent
    when: ansible_os_family=="RedHat"
  - name: stop service - ubuntu server
    service: 
     name: apache2
     state: stopped  
    when: ansible_os_family=="Debian"
  - name: uninstall apache2 - ubuntu server 
    apt:
     name: apache2
     state: absent
    when: ansible_os_family=="Debian"
  

    